[project]
name = "hippunfold-plot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.2",
    "nilearn>=0.10.4",
]
